export const ACTION = {
  ADD_NEW_TODO: "ADD_NEW_TODO",
  SAVE_NEW_TODO: "SAVE_NEW_TODO",
  DELETE_TODO: "DELETE_TODO",
  EDIT_TODO: "EDIT_TODO",
  CANCEL_ADDING_NEW_TODO: "CANCEL_ADDING_NEW_TODO",
  UPDATE_NEW_TODO_TITLE: "UPDATE_NEW_TODO_TITLE",
  UPDATE_NEW_TODO_CONTENT: "UPDATE_NEW_TODO_CONTENT",
  UPDATE_NEW_TODO_DATE: "UPDATE_NEW_TODO_DATE",
  INIT_TODO_LIST_FROM_LOCAL_STORAGE: "INIT_TODO_LIST_FROM_LOCAL_STORAGE",
  UPDATE_SERARCH_INPUT: "UPDATE_SERARCH_INPUT",
};
